### PR TITLE
updated sample_length to 700

### PR DESCRIPTION
**Pull request by abernkopf**

### CODE REVIEW

**Comment by jstypka** [comment]
Hey @abernkopf, thanks for the PR!

The `SAMPLE_LENGTH` setting is specific for every usecase, so should always be adjusted by the user. I don't really see a reason to have the default value 700 instead of 200, do you have some suggestions why it would be better?

**Comment by abernkopf** [comment]
Hey @jstypka, I actually was just trying to update the forked version I'm working on. I need the sample length to be longer when when installed because it's being used in part of an automated training script of documents that can be up to 23k words long, but are on average 700 words.

So I think I just goofed here, like I said, just trying to update a forked version.

**Comment by jstypka** [comment]
Makes sense! I'm going to close this PR then and good luck with your work!

**Comment by abernkopf** [comment]
All good, thanks!

**Pull request closed without merging**
