### PR TITLE
Make magpie great again

### PR DESCRIPTION
**Pull request by jstypka**
Few things here:
  - removed the dependency on keras.Graph object which was removed from Keras some time ago
  - bumped the Keras version to the newest one
  - added functions to easily save & load the trained models from disk
  - remove hardcoded `embedding_size` from config and infer it dynamically (bugfix)
  - update the docs for installation and IO

For the review process, it's easiest to look commit by commit.

@kaplun

### CODE REVIEW

**Comment by jstypka** [comment]
ping @jacquerie @kaplun

**Comment by jacquerie** [comment]
ACK, but I currently don't have time to look at this. It will happen sometime during this weekend. I have to add that "Make ___ great again" is not so funny anymore...

**Comment by jstypka** [comment]
Haha, to continue with the joke - I understand it's "Invenio first!", but can it be maybe "Magpie second"? ;-)

**Comment by jstypka** [comment]
Think about it another way - if there are no tests, we can't break it! ;)

**Comment by kaplun** [comment]
:smile: 
Not sure if @jacquerie has time for a review this week. Otherwise for me you can merge it

**Pull request merged**
